import { SpriteProps } from './@core/Sprite';

const spriteData: { [index: string]: SpriteProps } = {
    ui: {
        src: './assets/ui2.png',
        sheet: {
            'self-select': [
                [4, 0],
                [5, 0],
            ],
            select: [[4, 0]],
            dot: [[1, 0]],
            solid: [[0, 1]],
        },
    },
    stones: {
        src: './assets/stones2.png',
        frameWidth: 170,
        opacity: 1,
        frameHeight: 170,
        sheet: {
            '1': [[0, 0]],
            '2': [[1, 0]],
            '3': [[2, 0]],
            '4': [[0, 1]],
            '5': [[1, 1]],
            '6': [[2, 1]],
            '7': [[0, 2]],
            '8': [[1, 2]],
            '9': [[2, 2]],
            '10': [[0, 3]],
            '11': [[1, 3]],
            '12': [[2, 3]],
            '13': [[0, 4]],
            '14': [[1, 4]],
            '15': [[2, 4]],
            '16': [[0, 5]],
            '17': [[1, 5]],
            '18': [[2, 5]],
        },
    },
    player: {
        src: './assets/player6464.png',
        frameWidth: 21,
        frameHeight: 21,
        frameTime: 300,
        sheet: {
            default: [[0, 2]],
            walk: [
                [1, 2],
                [2, 2],
            ],
            action: [
                [0, 1],
                [2, 1],
            ],
        },
    },
    objects: {
        src: './assets/objects2.png',
        frameWidth: 20,
        frameHeight: 20,
        sheet: {
            floor: [[0, 0]],
            wall: [[1, 0]],
            'workstation-1': [[0, 1]],
            'workstation-2': [[1, 1]],
            'coffee-machine': [[2, 1]],
            'coffee-machine-empty': [[3, 1]],
            pizza: [[4, 1]],
            plant: [[0, 2]],
            arrow: [[0, 3]],
            bigtree1: [[4, 2]],
            bigtree2: [[4, 3]],
            midtree1: [[5, 2]],
            midtree2: [[5, 3]],
            smalltree: [[6, 2]],
        },
    },
    buildings: {
        src: './assets/town.png',
        frameWidth: 128,
        frameHeight: 128,
        opacity: 1,
        sheet: {
            default: [[1, 0]],
            blue: [[1, 5]],
            brick: [[0, 7]],
            roof: [[1, 7]],
            wood2: [[2, 7]],
            stone: [[3, 7]],
            cobble: [[0, 6]],
            green: [[1, 6]],
            door: [[2, 6]],
            longwindow: [[3, 6]],
            leftroof: [[0, 5]],
            midroof: [[1, 5]],
            rightroof: [[2, 5]],
            door2: [[3, 5]],
            halfcobble: [[0, 4]],
            halfwood3: [[1, 4]],
            halfstone: [[3, 4]],
            wood3: [[2, 4]],
            platerBox: [[0, 3]],
            sally: [[0, 0]],
            henry: [[0, 1]],
            megan: [[1, 0]],
            paul: [[1, 1]],
            george: [[2, 0]],
            lava: [[0, 2]],
            lava2: [[1, 2]],
            deadgrass: [[2, 2]],
            asfault: [[3, 2]],
            asfault2: [[3, 1]],
        },
    },
    ship: {
        src: '/assets/ship.png',
        frameWidth: 128,
        frameHeight: 128,
        opacity: 1,
        sheet: {
            '1': [[0, 0]],
            '2': [[1, 0]],
            '3': [[2, 0]],
            '4': [[3, 0]],
            '5': [[0, 1]],
            '6': [[1, 1]],
            '7': [[2, 1]],
            '8': [[3, 1]],
            '9': [[0, 2]],
            '10': [[1, 2]],
            '11': [[2, 2]],
            '12': [[3, 2]],
            '13': [[0, 3]],
            '14': [[1, 3]],
            '15': [[2, 3]],
            '16': [[3, 3]],
        },
    },
    tar2: {
        src: './assets/blackwatercolor.png',
        frameWidth: 200,
        frameHeight: 200,
        opacity: 1,
        sheet: {
            default: [[0, 0]],
            1: [[1, 0]],
            2: [[2, 0]],
            3: [[2, 0]],
            4: [[2, 0]],
        },
    },
    tar: {
        src: './assets/tar2.png',
        frameWidth: 100,
        frameHeight: 100,
        sheet: {
            static: [[4, 0]],
            default: [
                [0, 5],
                [1, 5],
                [2, 5],
                [3, 5],
                [4, 5],
                [0, 4],
                [1, 4],
                [2, 4],
                [3, 4],
                [4, 4],
                [0, 3],
                [1, 3],
                [2, 3],
                [3, 3],
                [4, 3],
                [0, 2],
                [1, 2],
                [2, 2],
                [3, 2],
                [4, 2],
                [0, 1],
                [1, 1],
                [2, 1],
                [3, 1],
                [4, 1],
                [0, 0],
                [1, 0],
                [2, 0],
                [3, 0],
                // [4, 0],
            ],
        },
        opacity: 1,
        frameTime: 100,
    },
    footstep: {
        src: './assets/footstep.png',
        sheet: {
            default: [
                [0, 0],
                [2, 0],
            ],
        },
        opacity: 0.75,
        frameTime: 150,
    },
};

export default spriteData;
