import { SpriteProps } from './@core/Sprite';

const spriteData: { [index: string]: SpriteProps } = {
    ui: {
        src: './assets/ui.png',
        sheet: {
            'self-select': [
                [4, 0],
                [5, 0],
            ],
            select: [[4, 0]],
            dot: [[1, 0]],
            solid: [[0, 1]],
        },
    },
    stones: {
        src: './assets/stones20x20.png',
        frameWidth: 40,
        frameHeight: 40,
        sheet: {
            '1': [[0, 0]],
            '2': [[1, 0]],
            '3': [[2, 0]],
            '4': [[0, 1]],
            '5': [[1, 1]],
            '6': [[2, 1]],
            '7': [[0, 2]],
            '8': [[1, 2]],
            '9': [[2, 2]],
            '10': [[0, 3]],
            '11': [[1, 3]],
            '12': [[2, 3]],
            '13': [[0, 4]],
            '14': [[1, 4]],
            '15': [[2, 4]],
            '16': [[0, 5]],
            '17': [[1, 5]],
            '18': [[2, 5]],
        },
    },
    player: {
        src: './assets/player.png',
        frameWidth: 20,
        frameHeight: 20,
        frameTime: 300,
        sheet: {
            default: [[0, 2]],
            walk: [
                [1, 2],
                [2, 2],
            ],
            action: [
                [0, 1],
                [2, 1],
            ],
        },
    },
    objects: {
        src: './assets/objects.png',
        frameWidth: 20,
        frameHeight: 20,
        sheet: {
            floor: [[0, 0]],
            wall: [[1, 0]],
            'workstation-1': [[0, 1]],
            'workstation-2': [[1, 1]],
            'coffee-machine': [[2, 1]],
            'coffee-machine-empty': [[3, 1]],
            pizza: [[4, 1]],
            plant: [[0, 2]],
            arrow: [[0, 3]],
            bigtree1: [[4, 2]],
            bigtree2: [[4, 3]],
            midtree1: [[5, 2]],
            midtree2: [[5, 3]],
            smalltree: [[6, 2]],
        },
    },
    tar2: {
        src: './assets/blackwatercolor.png',
        frameWidth: 200,
        frameHeight: 200,
        opacity: 1,
        sheet: {
            default: [[0, 0]],
            1: [[1, 0]],
            2: [[2, 0]],
            3: [[2, 0]],
            4: [[2, 0]],
        },
    },
    tar: {
        src: './assets/tar2.png',
        frameWidth: 100,
        frameHeight: 100,
        sheet: {
            static: [[4, 0]],
            default: [
                [0, 5],
                [1, 5],
                [2, 5],
                [3, 5],
                [4, 5],
                [0, 4],
                [1, 4],
                [2, 4],
                [3, 4],
                [4, 4],
                [0, 3],
                [1, 3],
                [2, 3],
                [3, 3],
                [4, 3],
                [0, 2],
                [1, 2],
                [2, 2],
                [3, 2],
                [4, 2],
                [0, 1],
                [1, 1],
                [2, 1],
                [3, 1],
                [4, 1],
                [0, 0],
                [1, 0],
                [2, 0],
                [3, 0],
                // [4, 0],
            ],
        },
        opacity: 1,
        frameTime: 100,
    },
    footstep: {
        src: './assets/footstep.png',
        sheet: {
            default: [
                [0, 0],
                [2, 0],
            ],
        },
        opacity: 0.75,
        frameTime: 150,
    },
};

export default spriteData;
